# Generated by Django 6.0.6 on 2026-06-04 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom commercial')),
                ('generic_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom générique')),
                ('dosage', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dosage')),
                ('form', models.CharField(blank=True, max_length=100, null=True, verbose_name='Forme pharmaceutique')),
                ('manufacturer', models.CharField(blank=True, max_length=200, null=True, verbose_name='Fabricant')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Prix d'achat")),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix de vente')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Quantité en stock')),
                ('min_stock', models.IntegerField(default=5, verbose_name='Stock minimum')),
                ('lot_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de lot')),
                ('expiry_date', models.DateField(verbose_name="Date d'expiration")),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Code-barres')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Emplacement')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='medications/', verbose_name='Image produit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medications', to='medications.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Médicament',
                'verbose_name_plural': 'Médicaments',
                'ordering': ['name'],
            },
        ),
    ]
