# Generated by Django 6.0.6 on 2026-06-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de facture')),
                ('insurance_coverage_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Part assurance')),
                ('client_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Part client')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant total')),
                ('status', models.CharField(choices=[('PENDING', 'En attente (Pharmacie)'), ('COMPLETED', 'Terminée (Caisse)'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('payment_method', models.CharField(choices=[('CASH', 'Espèces'), ('MOBILE_MONEY', 'Mobile Money'), ('CARD', 'Carte')], default='CASH', max_length=20, verbose_name='Mode de paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix unitaire')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix total')),
            ],
            options={
                'verbose_name': 'Article de vente',
                'verbose_name_plural': 'Articles de vente',
            },
        ),
    ]
