# Generated by Django 6.0.6 on 2026-06-04 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurance', '0001_initial'),
        ('medications', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cashier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_sales', to=settings.AUTH_USER_MODEL, verbose_name='Caissier'),
        ),
        migrations.AddField(
            model_name='sale',
            name='insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance.insurance', verbose_name='Assurance'),
        ),
        migrations.AddField(
            model_name='sale',
            name='pharmacist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_sales', to=settings.AUTH_USER_MODEL, verbose_name='Pharmacien'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medications.medication', verbose_name='Médicament'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale', verbose_name='Vente'),
        ),
    ]
