# Generated by Django 6.0.6 on 2026-06-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Ma Pharmacie', max_length=200, verbose_name='Nom de la pharmacie')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Logo')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('currency', models.CharField(default='FCFA', max_length=10, verbose_name='Devise')),
                ('tva_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taux TVA (%)')),
                ('receipt_header', models.TextField(blank=True, null=True, verbose_name='En-tête des tickets')),
                ('receipt_footer', models.TextField(blank=True, null=True, verbose_name='Pied de page des tickets')),
            ],
            options={
                'verbose_name': 'Paramètres de la pharmacie',
                'verbose_name_plural': 'Paramètres de la pharmacie',
            },
        ),
    ]
